apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: katt-kaniko-build-
spec:
  entrypoint: build
  arguments:
    parameters:
      - name: repo
      - name: revision
      - name: source
      - name: destination
      - name: dockerfile
  templates:
    - name: build
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
              repo: "{{workflow.parameters.repo}}"
              revision: "{{workflow.parameters.revision}}"
      container:
        image: gcr.io/kaniko-project/executor
        args:
          - "--context=/src"
          - "--dockerfile={{workflow.parameters.dockerfile}}"
          - "--destination={{workflow.parameters.destination}}"
          - "--build-arg"
          - "IMAGE={{workflow.parameters.source}}"
          - "--insecure"
          - "--insecure-pull"
  securityContext:
    runAsNonRoot: false
