repo: https://github.com/letfn/katt-kaniko
revision: master

build_dockerfile: Dockerfile.build
build_upstream_source: "gcr.io/kaniko-project/executor:v1.6.0-debug"
build_source: "k3d-hub.defn.ooo:5000/gcr.io/kaniko-project_executor_v1.6.0-debug"
build_destination: "k3d-hub.defn.ooo:5000/kaniko-project/executor:v1.6.0-debug"
